### ISSUE TITLE
Remove event

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-android-eventcapture#21]
Add support for removing events. Add an icon for deleting the event to the event form screen for existing events. The delete icon must have a bit of distance from the save icon to avoid mistakes. The delete event needs a confirmation dialog. In other words, to delete an event one must first click on the event in the main list, then click the delete icon (trash can icon) from the top menu.

**Comment by russnes** [comment]
I think there might be some limitations in the web api for this. Deleting events on the server may be difficult, but deleting events that only exist on the device should work.

**Comment by larshelge** [comment]
This depends on us first developing "soft deletes" on the server, and delete event support in the API. Blocked for now. 

https://blueprints.launchpad.net/dhis2/+spec/soft-event-delete
