### ISSUE TITLE
List of existing events takes long to load with many events

### ISSUE THREAD

**Issue by russnes** [dhis2/dhis2-android-eventcapture#29]
The "Registered Events" List takes a long time to show result if the number of events is high. Should implement some way to show the list immediately (perhaps first 5 items) and then add to the list as the loader progresses.

**Comment by arazabishov** [comment]
This is fixed now in new (alpha) version of event capture. 
https://github.com/dhis2/dhis2-android-eventcapture/releases/tag/0.5.1
