### ISSUE TITLE
Visual clue when reaching end of page

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-android-eventcapture#41]
When scrolling down and reaching end the page (form) then app should give a visual clue that you have reached the end. This can be similar to how the Gmail app displays a blue animation showing up from below the screen.

In field testing, users were sometimes confused when reaching end of page and continued to try to scroll downwards.

**Comment by arazabishov** [comment]
I am afraid that animation is used when there is more data to load (circular progress bar at the bottom of the list). Instead, we can have a button which will allow to jump to next section.
