### ISSUE TITLE
Clear value in option set field

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-android-eventcapture#42]
In data capture fields of type option set, there has to be a function for clearing the current value.

A user might want to clear a selected value and select none of the available options in the option set.

**Comment by arazabishov** [comment]
What if we will do next:
1) Replace "show options dialog" with "clear entry" button.
2) Role of "show options dialog" button now will play the field itself. When user clicks it, dialog shows up.

What do you think?
