### ISSUE TITLE
Hide keyboard for option set fields

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-android-eventcapture#43]
When capturing data for fields of type option set, the device keyboard should be hidden.

This behavior only seems to happen on certain devices including Samsung G S 3 tablets.

**Comment by arazabishov** [comment]
That is very strange, since the option set field is not even focusable (it should not trigger keyboard). It seems to be one of the bugs of Samsung firmwares.

**Comment by russnes** [comment]
I think Lars means the edit text for filtering options Araz, maybe you misunderstood? Anyways, it's hard to reproduce because it doesn't happen on either of my devices (I think it's because they're 4.4+)
