### ISSUE TITLE
Debug information for errors

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-android-eventcapture#44]
Currently when an event fails to sync to the central server, a label showing "Error" is displayed next to the event. The app should display more information to make it possible to understand what went wrong. The info is intended for technical people for debugging purposes.

**Comment by arazabishov** [comment]
I am not sure this is exactly what you are looking for, but you can tap on error status in order to see the general description of error. https://github.com/dhis2/dhis2-android-eventcapture/issues/23

**Comment by russnes** [comment]
I'll have to investigate but I think there's a difference in how error info is stored. Sometimes the error that is returned is an internal server error (500), so it returns a stack trace, but in other cases it is a message returned from the WebAPI (for example a duplicate or missing priviledge).

**Comment by russnes** [comment]
Now shows stack trace or DHIS 2 error message when clicking status icon
