### ISSUE TITLE
Show error indicator in registered events list if event has failed to upload (is linked to a FailedItem)

### ISSUE THREAD

**Issue by russnes** [dhis2/dhis2-android-eventcapture#5]
Show error indicator in registered events list if event has failed to upload (is linked to a FailedItem).

If the server returns status: ERROR when sending data to server, a FailedItem is created and linked with the item (Event, Enrollment, Tracked Entity Instance) there should be an indicator showing this to the user, similar to the indicator showing that an item is "Not yet synced with server" in SelectProgramFragment.

**Comment by arazabishov** [comment]
Implemented error indicator in SelectProgramFragment for list of registered events.
