### ISSUE TITLE
Dynamic data elements / columns in list of events

### ISSUE THREAD

**Issue by russnes** [dhis2/dhis2-android-eventcapture#50]
This is now hard coded to 3, and if there are less than 3 available - the remaining fields will be left empty. Should implement a dynamic adapter that can show number of elements based on the program. Should be set a maximum number of elements to display so it doesn't get too crowded.

**Comment by arazabishov** [comment]
see https://github.com/dhis2/dhis2-android-eventcapture/issues/46
