### ISSUE TITLE
Adding a new data element in existing program does not show up in android

### ISSUE THREAD

**Issue by sultanahamer** [dhis2/dhis2-android-eventcapture#63]
I create a program with say 2 data elements and open that program in android, it shows up well. Now I goto dhis, add a new data element to the program, open it in android, and the new data element does not show up.

**Comment by russnes** [comment]
Hi @sultanahamer 
The data elements are loaded through the program, so you will have to update the program version on the web to trigger an update on the app.

**Comment by sultanahamer** [comment]
Hi @simernes 
That worked out. Thanks for helping us out.
