### ISSUE TITLE
Programs can be accessed even if they are not assigned to a user role

### ISSUE THREAD

**Issue by ArchanaChillala** [dhis2/dhis2-android-eventcapture#65]
Programs can be accessed even if they are not assigned to a user role.
In DHIS web app, they need to be assigned to a role before they can be used. But, in the android app, programs unassigned to any user role can also be accessed for entering data. Currently using DHIS Version 2.22 and Build revision 21763.

**Comment by arazabishov** [comment]
This should be fixed in latest alpha release.
