### ISSUE TITLE
Form allows to 'complete' even if mandatory data elements are left blank.

### ISSUE THREAD

**Issue by ArchanaChillala** [dhis2/dhis2-android-eventcapture#66]
Even if a data element is made mandatory, the data entry form is able to ‘complete’ and save even without entering its value. Probably, an alert message asking user to fill in the mandatory fields before completing the form might fix this.

**Comment by russnes** [comment]
Hi,

this should be implemented in the latest release for 2.22. Can you please verify if it is still an issue?

**Comment by ArchanaChillala** [comment]
​Thanks, Simen. It's fixed. ​

Archana Chillala
Application Developer
Email archanac@thoughtworks.com
Telephone +91 9100960533 <+91+9100960533>
[image: ThoughtWorks]
http://www.thoughtworks.com/?utm_campaign=archana-chillala-signature&utm_medium=email&utm_source=thoughtworks-email-signature-generator
