### ISSUE TITLE
Description of report date not respected

### ISSUE THREAD

**Issue by larshelge** [dhis2/dhis2-android-eventcapture#67]
The ProgramStage.excecutionDateLabel defines the label to use for the input field for the execution date / reporting date. This label is not being rendered in the new event screen.

**Comment by erlingfjelstad** [comment]
Patch provided for legacy Event Capture. Will leave issue open for new Event capture until fixed there

**Comment by arazabishov** [comment]
Fixed in develop branch as well: 472b7131c983300e91d5810e12163ac9e08e0535
