### ISSUE TITLE
UI doesn't update correctly on change for assign program rule

### ISSUE THREAD

**Issue by oysteinga** [dhis2/dhis2-android-eventcapture#69]
It doesn't update field automatically on change at all times.
Guessing either assign rule isn't triggered correctly, or trouble with updating the UI.

To reproduce on BID server:
1. Create event with values for "expires < 4 weeks" in all sections
2. Create new event, enter values for "stock wasted - expired" (should be subtracted from "expires < 4 weeks")
3. "expires < 4 weeks" is sometimes updated, sometimes not.
4. Switching back and forth between sections and going back to the edited section, updates the field as it should.

**Comment by arazabishov** [comment]
Fixed for latest release.
